version: "3.9"
services:
  app:
    container_name: tasklist
    build:
      context: .
      dockerfile: Dockerfile
    image: tasklist:latest
    restart: always
    init: true
    ports:
      - "5001:5001"