name: Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        env:
          YOUR_SECRET: ${{ secrets.YOUR_SECRET }}
        with:
          host: ${{ secrets.HOST }} # ganti dengan IP atau hostname
          username: ${{ secrets.USERNAME }} # ganti dengan username
          password: ${{ secrets.PASSWORD }} # ganti dengan password
          port: 45022 # port yang Anda inginkan
          script: |
            # Mulai SSH agent
            eval $(ssh-agent -s)
            # Tambahkan private key
            ssh-add /home/daytaskt/.ssh/id_ed25519

            # Update kode
            git pull origin master

            # Install dependencies
            npm install

            # Build aplikasi
            npx babel src --out-dir . --ignore node_modules
